### ISSUE TITLE
Support for output to CSV file

### ISSUE THREAD

**Issue by kelvinharron** [asarkar/build-time-tracker#22]
Hi there! Thanks for supporting this library. I've been using the original version from passy as I need to document how bad our build times are and demonstrate with data, how much of an improvement on average each effort to reduce them achieves.

The original library supports writing to .csv files which I've been using, do you plan to provide support for anything similar? I don't see any documentation so I'm not sure it's supported here.

**Comment by asarkar** [comment]
It shouldn't be difficult to write to CSV. Can you show an example of what it looks like from the old plugin?

**Comment by kelvinharron** [comment]
Hey @asarkar thanks for replying! Below I've attached an example output CSV. I'll check out the branch you have and let you know how it looks. I believe I'm right in saying the .csv shouldn't spell out exactly what task you did but whatever tool you parse it with should know enough about x amount of tasks = unit test build vs ktlint or assembleDebug.

[wednesday-5th-may-times.csv](https://github.com/asarkar/build-time-tracker/files/6459329/wednesday-5th-may-times.csv)

I had appendHeaders enabled but I don't see much value from it.

**Comment by asarkar** [comment]
> the .csv shouldn't spell out exactly what task you did but whatever tool you parse it with should know enough about x amount of tasks = unit test build vs ktlint or assembleDebug.

The CSV I created is identical to the console output and hence provides the info you’re looking for.

> Could not find method buildTimeTracker()

Not sure about this error, I’ll verify with a Groovy build script. What Gradle version are you running?

**Comment by asarkar** [comment]
I tested with a Groovy project that uses Gradle 6.6.1 and it worked as expected. There was an unrelated bug with resolving the `csvFilePath` that I've fixed on the `3.0.x` branch.
```
import com.asarkar.gradle.buildtimetracker.Output
buildTimeTracker {
    output = Output.CSV
}
```

The CSV file gets generated at `build/reports/buildTimeTracker/build.csv` by default, and looks like the following:
```
:metrics-starter:compileKotlin,1S,20%,█
```

**Comment by kelvinharron** [comment]
Thanks for that as I didn't know about `mavenLocal()`. I can verify CSV output locally and I'm able to make changes and sync my project to reflect them (hardcoded `APPEND` in line 76 of `Printer.kt`). The default behaviour is overwriting the .csv each time which for my use case isn't ideal but can suit it with adjustments and I'm sure others too.

Here's exactly what I want to do and I think the passy implementation allows for:
> I want our team whole to automatically record all the invocations across our machines for a sprint or two. As we make adjustments to optimise and improve our poor build/gradle time, we can illustrate the difference with a measured change. Using .csv files will allow us to visually plot these changes and highlight regressions / bad local setup.

I don't wish to hijack the feature development of your library as its use-case in the console keeps it focused. Having a ton of options to configure it might push others away from using it too. In reference to passys library, Ii was pulling all the outputs from each engineer being able to sort by step + use timestamp as a unique key and see the spec of the machine in question it would give more useful context. What do you think of those features?

**Comment by asarkar** [comment]
> The default behaviour is overwriting the .csv each time

This is intentional, consistent with console output, and in line with how most CI/CD works. It’s not the plugin’s job to record historical data; depending on your build system, there are more than one way to get around this.

> In reference to passys library, Ii was pulling all the outputs from each engineer being able to sort by step + use timestamp as a unique key and see the spec of the machine

I won’t implement this. This plugin is focused on reporting the statistics from the current build; it doesn’t attempt to become a bloated analytics tool. Most teams have their own requirement, and I can’t cater to all of them. You’re welcome to continue using passy library in that case.

Thanks for opening this ticket. I’ll release v3.00 soon.

**Comment by kelvinharron** [comment]
Thanks for the input. Our current setup is pretty much out of the box. I did see suggestions on the passy issues about sending .csv across as JSON which actually makes a lot of sense and respects the intended approach you highlighted, as a different tool can then focus on analysis. Defiantly not something to bloat a single tool with I agree.

Happy to get the discussion going and appreciate your work on this!

**Comment by asarkar** [comment]
> sending .csv across as JSON

Perhaps you're referring to https://github.com/passy/build-time-tracker-plugin/issues/95.

To implement that feature, I think the simplest option is to extend the `CsvPrinter` and in the `close` method, make a multipart POST request to some endpoint. There's no need for the content to be JSON, as long as the endpoint can understand CSV. Since the plugin is written in kotlin, [ktor client](https://ktor.io/docs/getting-started-ktor-client.html) is a natural choice for the HTTP call.

Are you interested in making a PR to the 3.0.x branch?
