### ISSUE TITLE
[Feature Request] Total and daily summary of build time

### ISSUE THREAD

**Issue by hbb20** [asarkar/build-time-tracker#28]
Thank you for creating and maintaining this plugin. 

It will be great if this can also keep track of how much time my machine spend building Android project by day, month and total.

**Comment by asarkar** [comment]
The plugin’s job is to report build time, not participate in corporate data crunching. You’ll have to keep track of such data yourself.

**Comment by jakoss** [comment]
That's harsh.. I'm not working at corporate but i'd still like to know how much of my day is wasted on waiting for gradle to build my app

**Comment by asarkar** [comment]
@jakoss Sorry if my response came across as harsh, but my point stays. You can take the CSV file produced by the plugin and use the data within your CI pipeline for whatever purpose you see fit. “How much of my day is wasted waiting for Gradle” isn’t something this plugin is built to track.

**Comment by asarkar** [comment]
For the record, I’d like to add some details as to why I’m opposed to the proposal here. The plugin currently has no “memory”; in other words, it’s stateless. Tracking data over a period of time would require keeping state, a fundamental shift in the design, making development and maintenance complicated. More importantly, such a change is not necessary, because running a build is only the beginning of what a CI pipeline does; as I’ve stated, nothing stops a subsequent stage of the pipeline to read the CSV file, and perhaps put the data in a database, thus achieving statefulness.
Hopefully, this explains my stance on this matter.
