### ISSUE TITLE
Sort tasks in the output from lowest build time to highest

### ISSUE THREAD

**Issue by dmitry-ryadnenko-izettle** [asarkar/build-time-tracker#36]
Instead of sorting like this

```
:task1 | 27S | 30% | ███████████████████████████
:task2 | 17S | 19% | █████████████████
:task3 | 13S | 14% | █████████████
:task4 | 12S | 13% | ████████████
```

please let it be sorted like this by default.

```
:task4 | 12S | 13% | ████████████
:task3 | 13S | 14% | █████████████
:task2 | 17S | 19% | █████████████████
:task1 | 27S | 30% | ███████████████████████████
```

Or may be let it be an option.

The reason is that the tasks with the longest build times are the most interesting for us. By seeing which tasks run the longest we can detect potential build time issues. Or we can get insights about what should we focus on when optimizing build times.

Right now build times for the tasks with the longest build times are printed on the top of the output. Then there is a long tail of tasks with short build times. So in order for us to look at the most interesting tasks we need to scroll script output up. Which is very inconvenient and we may lose some insights because we won't do that scrolling after each build.

**Comment by dmitry-ryadnenko-izettle** [comment]
> If you’re not interested in short tasks, you can simply increase the threshold `minTaskDuration`. Would that work for you?

Thank you for the quick response. We have a lot of modules and sometimes we build the whole app and sometimes only this or that module. Minimum duration of tasks that we are interested in is different when we build small modules and big modules. So as result we have to keep `minTaskDuration` as small as possible (and btw, sometimes it's useful to see duration of tasks in milliseconds). So, I don't think we can resolve this in our project by adjusting `minTaskDuration`.

**Comment by asarkar** [comment]
I'm happy to report that the plugin supports sort ascending or descending now. I've pushed the changes to branch [issue-36](https://github.com/asarkar/build-time-tracker/tree/issue-36) as version `4.2.0-rc`. In order to use this version, you'll follow the following steps:

1. Pull down the branch locally.
2. Run `./gradlew clean publishToMavenLocal`.
3. Add the following **in your own project's** `settings.gradle`
   ```
   pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
   }
   ```
4. Update plugin version to `4.2.0-rc` in your project.
5. Set the new `sortBy` parameter in the plugin extension. See README for possible values.

Once I receive affirmative feedback, I'll publish it to Gradle plugin portal.

**Comment by dmitry-ryadnenko-izettle** [comment]
I've tried it. Works like a charm. One thing I noticed is that this syntax

```
buildTimeTracker {
    sortBy = ASC
}
```

doesn't work on our Groovy files. Though this one works.

```
buildTimeTracker {
    sortBy = com.asarkar.gradle.buildtimetracker.Sort.ASC
}
```

**Comment by asarkar** [comment]
Thanks for checking. `Sort` is an enum, so, it either needs to be imported, or fully-qualified. I'll note it in the README.

**Comment by asarkar** [comment]
v4.2.0 has been released.
